[tool.poetry]
name = "open-interpreter"
packages = [
    {include = "interpreter"},
]
version = "0.2.0"
description = "Let language models run code."
authors = ["Killian Lucas <killian@openinterpreter.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"

appdirs = "^1.4.4"
astor = "^0.8.1"
git-python = "^1.0.3"
inquirer = "^3.1.3"
litellm = "^1.15.10"
pyyaml = "^6.0.1"
rich = "^13.4.2"
six = "^1.16.0"
tiktoken = "^0.4.0"
tokentrim = "^0.1.13"
wget = "^3.2"
psutil = "^5.9.6"
pyreadline3 = {version = "^3.4.1", markers = "sys_platform == 'win32'"}
html2image = "^2.0.4.3"
ipykernel = "^6.26.0"
jupyter-client = "^8.6.0"
matplotlib = "^3.8.2"
toml = "^0.10.2"
posthog = "^3.1.0"
openai = "^1.6.1"

#Optional dependencies
opencv-python = { version = "^4.8.1.78", optional = true }
pyautogui = { version = "^0.9.54", optional = true }
plyer = { version = "^2.1.0", optional = true }
pywinctl = { version = "^0.3", optional = true }
semgrep = { version = "^1.52.0", optional = true }
yaspin = { version = "^3.0.1", optional = true }
pytesseract = { version = "^0.3.10", optional = true }

[tool.poetry.extras]
os = ["opencv-python", "pyautogui", "plyer", "pywinctl", "pytesseract"]
safe = ["semgrep", "yaspin"]

[tool.poetry.group.dev.dependencies]
black = "^23.10.1"
isort = "^5.12.0"
pre-commit = "^3.5.0"
pytest = "^7.4.0"
sniffio = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
interpreter = "interpreter:interpreter.start_terminal_interface"
cysecai = "interpreter:interpreter.start_terminal_interface"
i = "interpreter:interpreter.start_terminal_interface"
c = "interpreter:interpreter.start_terminal_interface"

[tool.black]
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
